image: php:5.6

before_script:
- composer install

services:
- mysql

variables:
  MYSQL_DATABASE: api_app
  MYSQL_ROOT_PASSWORD: ayshae

test:
    script:
      - phpunit --configuration phpunit_myapp.xml
